export const CONFIRM_LOGIN = "CONFIRM_LOGIN";
export const CONFIRM_LOGIN_SUCCESS = "CONFIRM_LOGIN_SUCCESS";
export const CONFIRM_LOGIN_ERROR = "CONFIRM_LOGIN_ERROR";

export const CONFIRM_LOGOUT = "CONFIRM_LOGOUT";
export const CONFIRM_LOGOUT_SUCCESS = "CONFIRM_LOGOUT_SUCCESS";
export const CONFIRM_LOGOUT_ERROR = "CONFIRM_LOGOUT_ERROR";


